version: '3'

services:
    nginx:
        image: bitnami/nginx:1.14
        depends_on:
            - php-fpm
        ports:
            - 80:8080
        volumes:
            - ./web:/app
            - ./vhost.conf:/opt/bitnami/nginx/conf/vhosts/default.conf

    php-fpm:
        image: bitnami/php-fpm:7.2
        volumes:
            - ./web:/app

    mariadb:
        image: bitnami/mariadb:10.2
        environment:
            - MARIADB_ROOT_PASSWORD=blaat123
        ports:
            - 3306:3306
        volumes:
            - ./db:/bitnami/mariadb/data
