twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    date:
        format: m-d-y H:i
        timezone: Europe/Amsterdam
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        sourcebans:
            console_name: '%sourcebans.console_name%'
