index:
    path: /
    controller: SourceBans\Controller\DefaultController::index

appeal:
    path: /appeal
    controller: SourceBans\Controller\DefaultController::appeal

report:
    path: /report
    controller: SourceBans\Controller\DefaultController::report

login:
    path: /login
    controller: SourceBans\Controller\DefaultController::login

logout:
    path: /logout

bans:
    path: /bans
    controller: SourceBans\Controller\BansController::index

bans_export:
    path: /bans/export/{type}
    controller: SourceBans\Controller\BansController::export

admin_admins_index:
    path: /admin/admins
    controller: SourceBans\Controller\Admin\AdminsController::index

admin_admins_add:
    path: /admin/admins/add
    controller: SourceBans\Controller\Admin\AdminsController::add

admin_admins_edit:
    path: /admin/admins/edit/{id}
    controller: SourceBans\Controller\Admin\AdminsController::edit

admin_admins_delete:
    path: /admin/admins/delete/{id}
    controller: SourceBans\Controller\Admin\AdminsController::delete

admin_bans_add:
    path: /admin/bans/add
    controller: SourceBans\Controller\Admin\BansController::add

admin_bans_edit:
    path: /admin/bans/edit/{id}
    controller: SourceBans\Controller\Admin\BansController::edit

admin_bans_delete:
    path: /admin/bans/delete/{id}
    controller: SourceBans\Controller\Admin\BansController::delete

admin_bans_unban:
    path: /admin/bans/unban/{id}
    controller: SourceBans\Controller\Admin\BansController::unban

admin_games_index:
    path: /admin/games
    controller: SourceBans\Controller\Admin\GamesController::index

admin_games_add:
    path: /admin/games/add
    controller: SourceBans\Controller\Admin\GamesController::add

admin_games_edit:
    path: /admin/games/edit/{id}
    controller: SourceBans\Controller\Admin\GamesController::edit

admin_games_delete:
    path: /admin/games/delete/{id}
    controller: SourceBans\Controller\Admin\GamesController::delete

admin_groups_index:
    path: /admin/web-groups
    controller: SourceBans\Controller\Admin\GroupsController::index

admin_groups_add:
    path: /admin/web-groups/add
    controller: SourceBans\Controller\Admin\GroupsController::add

admin_groups_edit:
    path: /admin/web-groups/edit/{id}
    controller: SourceBans\Controller\Admin\GroupsController::edit

admin_groups_delete:
    path: /admin/web-groups/delete/{id}
    controller: SourceBans\Controller\Admin\GroupsController::delete

admin_server_groups_index:
    path: /admin/server-groups
    controller: SourceBans\Controller\Admin\ServerGroupsController::index

admin_server_groups_add:
    path: /admin/server-groups/add
    controller: SourceBans\Controller\Admin\ServerGroupsController::add

admin_server_groups_edit:
    path: /admin/server-groups/edit/{id}
    controller: SourceBans\Controller\Admin\ServerGroupsController::edit

admin_server_groups_delete:
    path: /admin/server-groups/delete/{id}
    controller: SourceBans\Controller\Admin\ServerGroupsController::delete

admin_servers_index:
    path: /admin/servers
    controller: SourceBans\Controller\Admin\ServersController::index

admin_servers_add:
    path: /admin/servers/add
    controller: SourceBans\Controller\Admin\ServersController::add

admin_servers_edit:
    path: /admin/servers/edit/{id}
    controller: SourceBans\Controller\Admin\ServersController::edit

admin_servers_delete:
    path: /admin/servers/delete/{id}
    controller: SourceBans\Controller\Admin\ServersController::delete
