imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        parameters: "%sourcebans%"
        settings: "@sourcebans.core.settings"

# Assetic Configuration
assetic:
    read_from:      "%kernel.root_dir%/../public_html"
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["SourceBansCoreBundle"]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"
        server_version: 5.7
        mapping_types:
            enum: string
        types:
            timestamp: SourceBans\CoreBundle\Doctrine\DBAL\TimestampType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        default_repository_class: Rb\Specification\Doctrine\SpecificationRepository
        dql:
            datetime_functions:
                adddate: SourceBans\CoreBundle\Doctrine\ORM\AddDateFunction

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

stfalcon_tinymce:
    tinymce_jquery: true
    language: "%locale%"

    theme:
        advanced:
            width: 750
            height: 250
            menubar: false
            statusbar: false
            plugins:
                - "pagebreak layer table save hr image link charmap emoticons spellchecker insertdatetime preview media textcolor"
                - "searchreplace print contextmenu paste directionality fullscreen noneditable visualchars nonbreaking template"
            toolbar1: "bold italic underline strikethrough | bullist numlist blockquote | alignleft aligncenter alignright alignjustify | link unlink image media"
            toolbar2: "formatselect | subscript superscript forecolor | hr charmap emoticons | removeformat"
            toolbar_items_size: "small"
            schema: "html5"

parameters:
    version:        2.0.0-dev
    version_url:    https://api.github.com/repos/GameConnect/SourceBans/releases/latest
    pattern_status: /# +([0-9]+) +(?:[0-9]+ +)?"(.+)" +(STEAM_[0-9]:[0-9]:[0-9]+|\[U:[0-9]:[0-9]+\]) +([0-9:]+) +([0-9]+) +([0-9]+) +([a-zA-Z]+) +([0-9.:]+)/
    pattern_steam:  /^STEAM_[0-9]:[0-9]:[0-9]+|\[U:[0-9]:[0-9]+\]$/i
